require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/dogeared/cli'
require_relative '../lib/dogeared/version'
require_relative '../lib/dogeared/book'
require_relative '../lib/dogeared/genre'
require_relative '../lib/dogeared/scraper'
