require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/book_chooser/cli'
require_relative '../lib/book_chooser/version'
require_relative '../lib/book_chooser/book'
require_relative '../lib/book_chooser/genre'
require_relative '../lib/book_chooser/scraper'
